### ISSUE TITLE
No explicit license statement any more

### ISSUE THREAD

**Issue by tillea** [dkoboldt/varscan#12]
Hi,

the old webseite was specifying a non-profit license (Non-Profit Open Software License 3.0).  I can not find any license statement on the Github pages.  I formerly several times tried to seek contact about the licensing since I would like to distribute varscan in Debian main.  Unfortunately the non-profit restrictions conflicts with the Debian Free Software Guidelines and makes the software non-free.

If no license is specified at all as it is now from a distribution point of view its is non-free as well since we do not have any explicite permission to distribute the code.

It would be great if you would consider a free license like GPL, BSD or similar.

Thanks for considering

```
 Andreas.
```

**Comment by serge2016** [comment]
+1

**Comment by dkoboldt** [comment]
Andreas, sorry it took me this long to see your note, but the license statement is in the VarScan README file that's included with new releases. It essentially states that VarScan is free for non-commercial use, but commercial users must obtain a license through Washington University.

**Comment by tillea** [comment]
Hi Dan,

do you think there is room for discussion about this non-profit restriction and if yes, who is the person to discuss with.  As I mentioned above we would like to include varscan into official Debian but we can not since Debian Free Software Guidelines are considering this restriction as non-free.

Kind regards

        Andreas.
