### ISSUE TITLE
how to  output wildtype  site via VarScan with SNP calling ?

### ISSUE THREAD

**Issue by WinterLi1993** [dkoboldt/varscan#14]
HI,
    I wanna use VarScan to produce calls at variant sites and confident reference sites, but I can not find any parameters .

**Comment by dkoboldt** [comment]
Hello, you can do this using the VarScan "mpileup2cns" command. However, it only works if you don't provide the "--variants" or "--output-vcf" parameters, as both of these force variant-position-only reporting.

Incidentally, for VarScan somatic, the --validation 1 parameter will force it to output wild-type calls with good coverage.

**Comment by goeckeritz** [comment]
Hi there, 

Is there a way to convert the resulting file with all positions to a vcf for use with bcftools?
