### ISSUE TITLE
VCF and tab interconversion

### ISSUE THREAD

**Issue by tedtoal** [dkoboldt/varscan#17]
I wanted to separate LOF and somatic HC and germline using processSomatic, but it requires a tabular input whereas I had generated VCF files.  I want those VCF files and I want VCF files with LOF separated.  It would be nice if all varscan commands that read tab-separated variant files could also read VCF files, and all commands that write files could write both kinds.  Also, it would be very nice if there were a "null" command that could simply read a file in one format and output it in the other.

**Comment by dkoboldt** [comment]
Ted, VarScan's processSomatic works on VCF files as of version 2.4.0, if I'm not mistaken.

**Comment by tedtoal** [comment]
Ok, thanks.  Does it auto-detect input file format, because I didn't see an option to specify it.
